const CONFIG = {
  API_URL: 'https://integra-backend-ynrd.onrender.com/api',
  FRONTEND_URL: 'https://integra-saude-psi.vercel.app',
  NOME_SISTEMA: 'Integrativo.App',
  VERSAO: '1.0.0',
  PLANOS: {
    freemium: {
      nome: 'Freemium',
      valor_mensal: 0,
      whatsapp: false,
      loja: false,
      nf: false,
      max_pacientes: 50,
      max_teleconsultas: 30,
      max_agendamentos: 70,
      max_whatsapp: 30,
      recepcao: false,
      blog: false,
      rh: false,
      white_label: false,
      api_white_label: false,
      migracao: false,
      conciliacao: false,
      desconto_renovacao: 0
    },
    pro: {
      nome: 'Pro',
      valor_mensal: 54.90,
      valor_semestral: 274.50,
      valor_anual: 549,
      whatsapp: true,
      loja: true,
      nf: true,
      max_pacientes: 300,
      max_teleconsultas: 150,
      max_agendamentos: 500,
      max_whatsapp: 1000,
      recepcao: 1,
      blog: 10,
      rh: 'basico',
      white_label: true,
      api_white_label: false,
      migracao: true,
      conciliacao: false,
      desconto_renovacao: 0
    },
    premium: {
      nome: 'Premium',
      valor_mensal: 299.90,
      valor_semestral: 1499.50,
      valor_anual: 2999,
      whatsapp: true,
      loja: true,
      nf: true,
      max_pacientes: 1000,
      max_teleconsultas: Infinity,
      max_agendamentos: Infinity,
      max_whatsapp: Infinity,
      recepcao: 3,
      blog: Infinity,
      rh: 'completo',
      white_label: true,
      api_white_label: true,
      migracao: true,
      conciliacao: true,
      desconto_renovacao: 5
    },
    enterprise: {
      nome: 'Enterprise',
      valor_mensal: 599.90,
      valor_semestral: 2999.50,
      valor_anual: 5999,
      whatsapp: true,
      loja: true,
      nf: true,
      max_pacientes: Infinity,
      max_teleconsultas: Infinity,
      max_agendamentos: Infinity,
      max_whatsapp: Infinity,
      recepcao: Infinity,
      blog: Infinity,
      rh: 'completo',
      white_label: true,
      api_white_label: true,
      migracao: true,
      conciliacao: true,
      certificado_a1_gratis: true,
      desconto_renovacao: 10
    }
  },
  PARCELAMENTO: {
    max_semestral: 3,
    max_anual: 4,
    sem_juros: true
  },
  PRAZOS: {
    arrependimento_dias: 10,
    reposicao_yoga_dias: 30,
    notificacao_renovacao_dias: 15
  },
  GATEWAYS: [
    { id: 'pagseguro', nome: 'PagSeguro', taxa_cartao: '3,99%', taxa_pix: '1,99%' },
    { id: 'pagbank', nome: 'PagBank', taxa_cartao: '3,99%', taxa_pix: '1,99%' },
    { id: 'asaas', nome: 'Asaas', taxa_cartao: '2,99%', taxa_pix: '1,99%' },
    { id: 'ton', nome: 'Ton', taxa_cartao: '1,99%', taxa_pix: '0,99%' },
    { id: 'mercadopago', nome: 'Mercado Pago', taxa_cartao: '3,99%', taxa_pix: '1,99%' },
    { id: 'efi', nome: 'Efi Bank', taxa_cartao: '1,99%', taxa_pix: '1,99%' },
    { id: 'cielo', nome: 'Cielo', taxa_cartao: 'Variável', taxa_pix: '1,99%' },
    { id: 'stone', nome: 'Stone', taxa_cartao: 'Variável', taxa_pix: '1,99%' }
  ],
  SUPORTE: {
    segunda: '10h - 19h',
    terca: '10h - 19h',
    quarta: '13h - 17h',
    quinta: '10h - 19h',
    sexta: '13h - 17h',
    sabado: 'Fechado',
    domingo: 'Fechado'
  }
};
window.CONFIG = CONFIG;